<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AutomaticOnlineHostComputer</RootNamespace>
    <AssemblyName>AutomaticOnlineHostComputer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Views\新文件夹\**" />
    <EmbeddedResource Remove="Views\新文件夹\**" />
    <None Remove="Views\新文件夹\**" />
    <Page Remove="Views\新文件夹\**" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\Controller\Dialogs\" />
    <Folder Include="Views\Crane\Dialogs\" />
    <Folder Include="Views\Machine\Dialogs\" />
    <Folder Include="Views\Process\Dialogs\" />
  </ItemGroup>
</Project>
